# General
length = "QP"
num_comps = 100

# Methods
method = { title = "Bristol Surprise Royal" }

# Calls
base_calls = "far"
bob_weight = -6
single_weight = -4
calls = [{ symbol = "x", place_notation = "16", weight = -8 },
        ]

#bobs_only = true

# Music
base_music = "none"
music = [
    # 56s & 65s
    { patterns = ["567890*", "*567890", "657890*", "*657890"], weight = 1 }, # Boost 5678s and 6578s

    # 4, 5, 6, 7, 8 and 9 Bell Runs
    { run_lengths = [4, 5, 6, 7, 8, 9] },
    
    # Near Misses
    { patterns = ["1234567809", "1234567980", "1234568790", "1234576890", "1234657890", "1235467890",
    			  "1243567890", "1324567890", "2134567890"], weight = 1 },
    
    # Combinations from named rows
    { patterns = ["*24680", "*975680", "x6x7x8x9x0"], weight = 1 }, # From Queens, Whittingtons and Tittums

    # Named Rows
    { patterns = [ "1234567890", "1256349078", "1286349750", "1325476980", # Rounds, Hagdyke, Heywood's, Priory/The Intermediate
                   "1357294680", "1357924680", "1539742860", "1627384950", # Princesses, Queens, Kennet, Tittums
                   "1864297530", "1875296430", "1896745230", "1987654320", # Yeovil Octaves, Hereford Octaves, Jacks, Jokers
                   "3124586790", "3124975680", "3216549870", "5432167890", # Burdette, Whittingtons, Rollercoaster, See-saw
                   "5647382910", "6543217890", "9753124680", "9753214680", # Exploded Tittums, Reverse Waterfall, Kings, Princes
                   "0987123456", "0987654321" ], weight = 1 },             # Waterfall, Backrounds

    # Undesirables
    { pattern = "*09", weight = -2, stroke = "back" }, # Slightly penalise 09s at back
]

# Courses
split_tenors = false

