# General
length = "QP"
num_comps = 100

# Methods
method = { title = "Plain Bob Triples" }

# Calls
base_calls = "near"
bob_weight = -4
single_weight = -6

# Part Head
part_head = "1423657"

# Music
base_music = "none"
music = [
    # 56s & 65s
    { patterns = ["*567", "*657"], weight = 1 }, # Boost 567s and 657s
    
    #crus
    { patterns = ["*457", "*467", "*547", "*567", "*647", "*657"], weight = 1 }, # Boost 457s, 467s, 547s, 567s, 647s and 657s
  
    # 4, 5, and 6 Bell Runs
    { run_lengths = [4, 5, 6] },
    
    # Combination Near Misses
    { patterns = ["1234576", "1234657", "1235467", "1243567", "1324567", "2134567",
                  "1235476", "1243657", "1324576", "1325476"], weight = 1 },

    # 567 combinations
    { patterns = ["*567", "*576", "*657",                 # From 567 and 576
                  "*675", "*756", "*765"], weight = 1 },  # From 756 and 765

    # 46s (Breakdown)
    { patterns = ["*46", "*246", "*746", "*7546"], weight = 1 },

    # Combinations from named rows
    { patterns = ["*246", "*346", "*347", "*357",    # From Queens, Whittingtons, Hagdyke
                  "*374", "*576", "*746", "*756",    # From Tittums, Bowbells, Princesses, Burdette
                  "*765", "x5x6x7x"], weight = 1 },  # From Rollercoaster, Tittums

    # Named Rows
    { patterns = [ "1234567", "1256347", "1275346", "1324576",  # Rounds, Hagdyke, Whittingtons, Bowbells
                   "1325476", "1352746", "1357246", "1432765",  # Priory/The Intermediate, Princesses, Queens, Rollercoaster
                   "1526374", "1674523", "1765243", "1765432",  # Tittums, Jacks, St Michael's, Jokers
                   "3124756", "4321567", "4536271", "7531246",  # Burdette, See-saw, Exploded Tittums, Kings
                   "7532146", "7654321"], weight = 1 },         # Princes, Backrounds
]

# Courses
split_tenors = true
