[package]
name = "monument"
version = "0.1.0"
edition = "2021"

[dependencies]
bellframe.path = "../../bellframe/"
bit-vec = "0.6"
gcd = "2.0"
index_vec = "0.1"
itertools = "0.10"
log = "0.3"
ordered-float = "2.8"
serde = { version = "1.0", features = ["derive"] }
num_cpus = "1.13"
