length = "peal"
method = "Bristol Surprise Major"

bob_weight = 0
bobs_only = true

non_duffer_courses = [
    { masks = ["*5678", "*5x678", "*8765", "*8x765"], both_strokes = true, any_bells = true },
    { masks = ["*6578", "*6x578", "*8x756"], both_strokes = true },
]
max_contiguous_duffer = 96
max_total_duffer = 256
