length = "peal"
method = "Bristol Surprise Major"

bob_weight = 0
bobs_only = true

non_duffer_courses = [
    { courses = ["*5678", "*5x678", "*8765", "*8x765"], any_stroke = true, any_bells = true },
    { courses = ["*6578", "*6x578", "*8x756"], any_stroke = true },
]
max_contiguous_duffer = 96
max_total_duffer = 256
