[package]
name = "monument_cli"
version = "0.2.0"
edition = "2021"

authors = ["Ben White-Horne <kneasle@gmail.com>"]
description = "CLI interface to Monument, a fast and flexible composing engine."
license = "MIT"
repository = "https://github.com/kneasle/ringing-monorepo"

[dependencies]
bellframe = { version = "0.5.0", path = "../../bellframe/", features = ["serde"] }
itertools = "0.10"
log = "0.4" # TODO: Bump this to 0.4
monument = { version = "0.2.0", path = "../lib/" }
pretty_logger = "0.1"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
toml = "0.5"

[dev-dependencies]
colored = "2.0"
difference = "2.0"
ordered-float = { version = "2.8", features = ["serde"] }

[[test]]
name = "integration"
path = "../integration_runner.rs"
harness = false
