[package]
name = "monument_cli"
version = "0.5.0"
edition = "2021"

authors = ["Ben White-Horne <kneasle@gmail.com>"]
description = "CLI interface to Monument, a fast and flexible composing engine."
readme = "../README.md"
license = "MIT"
repository = "https://github.com/kneasle/ringing-monorepo"

[dependencies]
anyhow = "1.0"
bellframe = { version = "0.8.0", path = "../../bellframe/", features = ["serde"] }
colored = "2.0"
ctrlc = "3.2"
difference = "2.0"
itertools = "0.10"
log = "0.4"
monument = { version = "0.5.0", path = "../lib/" }
ordered-float = "2.10"
ringing_utils = { version = "0.1.0", package = "kneasle_ringing_utils", path = "../../utils/" }
serde = { version = "1.0", features = ["derive"] }
simple_logger = "2.1"
structopt = "0.3"
toml = "0.5"

[dev-dependencies]
ordered-float = { version = "2.10", features = ["serde"] }
pulldown-cmark = "0.9"
rayon = "1.5"
serde_json = "1.0"
walkdir = "2.3"

[[test]]
name = "integration"
path = "../test/src/test.rs"
harness = false
