[package]
name = "monument_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
bellframe.path = "../../bellframe"
eframe = "0.15"
itertools = "0.10"
log = "0.3" # TODO: Bump this to 0.4
monument.path = "../lib"
number_prefix = "0.4"
pretty_logger = "0.1"
