[alias]
# Aliases `cargo bless` to running the integration test runner with the `bless` argument.  `-q`
# makes Cargo 'quiet' - i.e. it won't print any 'Compiling ...' stuff.  This is probably fine,
# because you've almost certainly run the tests before blessing.
bless = "-q test --test integration -- bless"
