length = "QP"

methods = [
    { name = "St Simeon's",  shorthand = "S", place_notation = "7.1.7.1.7.3.7,147",     stage = 7 },
    { name = "St Osmanna",   shorthand = "O", place_notation = "7.1.7.1.127.3.7,147",   stage = 7 },
    { name = "St Martina's", shorthand = "M", place_notation = "7.1.7.1.7.123.7,147",   stage = 7 },
    { name = "Ensbury",      shorthand = "E", place_notation = "7.1.7.1.127.123.7,147", stage = 7 },
]
method_count = { min = 200, max = 400 }

part_head = "134265"
splice_style = "calls"
splice_weight = -1

base_music = "none"

base_calls = "none"
calls = [
    { symbol = "", debug_symbol = "-", place_notation = "127" },
    { symbol = "s", place_notation = "12347" },
]
