length = "QP"
method = "Bristol Surprise Major"

# Punish calls more than usual.  This will prevent Monument from jamming consecutive calls together
# (e.g. HHsHHH) because the score added by the music will not outweigh the score lost from the
# calls
bob_weight = -5
single_weight = -7
