length = { min = 1250, max = 1299 }
base_calls = "far"
music_file = "music-8.toml"

bob_weight = -5
single_weight = -7

[method]
place_notation = "-34-14-56-1238-12-58-16-78,18"
name = "Ivy Was The Best Sheep"
stage = 8
