length = "QP"
method = "Bristol Surprise Major"

[[music]]
run_length = 4

[[music]]
run_lengths = [5, 6, 7]
show = false # Don't display runs longer than 4

[[music]]
pattern = "6578"

# Boost 5678s off the front
[[music]]
patterns = ["5678", "8765"]
weight.front = 3
weight.back = 3
