length = "practice"
methods = [
    "Cambridge Surprise Major",
    "Yorkshire Surprise Major",
    "Superlative Surprise Major",
    "Bristol Surprise Major",
    { title = "Cornwall Surprise Major", shorthand = "W" },
    { title = "Lessness Surprise Major", shorthand = "E" },
    "London Surprise Major",
]
method_count = { min = 32, max = 300 } # Require at least a whole lead of every method

# Boost 5678/8765s off the front
[[music]]
patterns = ["5678", "8765"]
weight.front = 3
