# This file specifies what arguments/structures are possible in which sections of Monument's input
# format

length = "peal"
# length = 5040
# length = { min = 5040, max = 5040 }
# Special values:
#   "practice"  -> { min = 0, max = 300 }
#   "QP"|"qp"   -> { min = 1250, max = 1350 }
#   "half peal" -> { min = 2500, max = 2600 }
#   "peal"      -> { min = 5000, max = 5200 }
num_comps = 10

# base_calls = "far"

[method]
place_notation = "-50-14.50-50.36.14-70.58.16-16.70-16-10,10"
name = "Bristol"
stage = 10
# These don't work (due to what I believe is a bug in serde):
# stage = "Royal"
# stage = "royal"
#(opt) lead_locations = { 0 = "LE", 20 = "HL" }

#     or
# [method]
# title = "Bristol Surprise Royal"
# lead_locations = { .. }

#     or
# method = "Bristol Surprise Royal"

[[calls]]
place_notation = "16"
symbol = "x"
#(opt) lead_location = "LE"
#(opt) calling_positions = "LIBFVXSMWH"

[[music]]
run_lengths = [5, 6, 7, 8]
#(opt) weight = 1

[[music]]
patterns = ["*7x8x9x0", "*657890"]
weight = 3
