length = "peal"
methods = [
    "Bristol Surprise Maximus",
    "Zanussi Surprise Maximus",
    "Avon Delight Maximus",
]
part_head = "165432"

# Punish calls more because Maximus generates too much music
bob_weight = -15
single_weight = -20
