# Music file for 9-bell complib music compositions

# 56s & 65s
[[music]]
patterns = ["*56789", "*65789"]  # Boost 567s and 657s
weight = 1

# 4, 5, 6, 7, and 8 Bell Runs
[[music]]
run_length = 4
weight = 1

[[music]]
run_lengths = [5, 6, 7, 8]
weight = 1
show = false  # Only show 4-bell runs

# Near Misses
[[music]]
patterns = ["123456798", "123456879", "123457689", "123465789", "123546789", "124356789",
            "132456789", "213456789"]
weight = 1
show = false

# Combinations from named rows
[[music]]
patterns = ["*468", "*987", "*2468",          # From Queens, Rollercoaster, Queens
            "*8495", "*97568", "*xxx7x8x9x"]  # From Tittums, Whittingtons, Tittums
weight = 1
show = false

# Named Rows
[[music]]
patterns = [ "123456789", "128634975", "132547698", "135729468",  # Rounds, Heywood's, Priory/The Intermediate, Princesses
             "135792468", "153974286", "162738495", "186429753",  # Queens, Kennet, Tittums, Yeovil Octaves
             "187529643",  # Hereford Octaves,
             #"187529643",  # The Octaves  # Leaving this commented out whilst waiting to see if this is a bug where it either should not be here or is mistyped, due to it being the same row as for Hereford Octaves
             "189674523", "198765432",  # Jacks, Jokers
             "312458679", "312497568", "321654987", "543216789",  # Burdette, Whittingtons, Rollercoaster, See-saw
             "564738291", "654321789", "975312468", "975321468",  # Exploded Tittums, Reverse Waterfall, Kings, Princes
             "987123456", "987654321"]                            # Waterfall, Backrounds
weight = 1
show = false
