[[music]]
run_length = 4

[[music]]
run_lengths = [5, 6, 7, 8]
show = false # Only show 4-bell runs

[[music]]
patterns = [
    "5678*", "*5678",
    "8765*", "*8765",
    "6578*", "*6578",
]

# Queens and Kings
[[music]]
patterns = ["13572468", "75312468"]
weight = 3
show = false

[[music]]
pattern = "*87"
stroke = "back"
weight = -0.7
name = "87s"
