# Music file for 8-bell complib music compositions
# Music is split into two sections, the first gives what music to display in the header (which has zero
# weighting) and the second gives the scoring that counts towards the total music score.

#--------------------------#
#- Displayed header music -#
#--------------------------#

[[music]]
preset = "crus"

[[music]]
patterns = ["5678", "6578"]

[[music]]
run_length = 4

[[music]]
preset = "5678 combinations"
weight.front = 0 # Only some 5678 combinations are scored, but the total count is displayed
weight.back = 0

[[music]]
pattern = "8765"

[[music]]
pattern = "87"
stroke = "back"
weight.back = 0 # Display these at backstroke but don't score them
name = "87s"

#-----------------#
#- Music scoring -#
#-----------------#

[[music]]
run_lengths = [5, 6, 7] # 4-bell runs are already scored
show = false

# Combination Near Misses
[[music]]
patterns = ["12345687", "12345768", "12346578", "12354678", "12435678", "13245678",
            "21345678", "12346587", "12354768", "12435687", "12436578", "12436587",
            "13245768", "13254768", "21345687", "21346587", "21436587"]
show = false

# 5678 combinations counted towards music score
[[music]]
patterns = ["5678", "6578", "7568", "7658", "8765"]
show = false

[[music]]
patterns = ["1357", "2468", "3468", "3478",  # From Queens, Whittingtons, Hagdyke
            "3578", "5768", "7468", "7568",  # From 3578s, Bowbells, Princesses, Burdette
            "7658", "8765"]        # From Rollercoaster, Esso-Blues
weight.back = 1 # Only score these at the back of the change
show = false

# Combination from tittums
[[music]]
pattern = "x5x6x7x8"
show = false

# Named Rows
[[music]]
patterns = [ "12345678", "12563478", "12753468", "13245768",  # Rounds, Hagdyke, Whittingtons, Bowbells
             "13254768", "13527468", "13572468", "14327658",  # Priory/The Intermediate, Princesses, Queens, Rollercoaster
             "15263748", "16745238", "17652438", "17654328",  # Tittums, Jacks, St Michael's, Jokers
             "31247568", "43215678", "56781234", "45362718",  # Burdette, See-saw, Saw-see, Exploded Tittums
             "65432178", "75312468", "75321468", "87123456",  # Reverse Waterfall, Kings, Princes, Waterfall
             "87654321" ]                                     # Backrounds
show = false

# TODO: Wraps
