# Music file for 6-bell complib music compositions
# Music is split into two sections, the first gives what music to display in the header (which has zero
# weighting) and the second gives the scoring that counts towards the total music score.

#--------------------------#
#- Displayed header music -#
#--------------------------#

# Display 65s at back
[[music]]
pattern = "65"
stroke = "back"
weight.back = 0

#-----------------#
#- Music scoring -#
#-----------------#

# 56s
[[music]]
pattern = "56"  # Boost 56s
weight.back = 1
show = false

# 4 and 5 Bell Runs
[[music]]
run_lengths = [4, 5]
show = false

# Combination Near Misses
[[music]]
patterns = ["123465", "123546", "124356", "132456", "213456", "124365",
            "132465", "132546", "213465", "213546", "214356", "214365"]
show = false

# Named Rows
[[music]]
patterns = [ "123456", "132546", "135246", "142536", # Rounds, Priory/The Intermediate, Queens, Tittums
             "145236", "154326", "213546", "321456", # Jacks, Jokers, Burdette, See-saw
             "341256", "342516", "531246", "532146", # Hagdyke, Exploded Tittums, Kings/Whittingtons, Princes
             "654321" ]                              # Backrounds
show = false
