# Music file for 6-bell complib music compositions

# 56s
[[music]]
patterns = ["*56"]  # Boost 56s
weight = 1

# 4 and 5 Bell Runs
[[music]]
run_length = 4
weight = 1

[[music]]
run_lengths = [5]
weight = 1
show = false  # Only show 4-bell runs

# Combination Near Misses
[[music]]
patterns = ["123465", "123546", "124356", "132456", "213456", "124365",
            "132465", "132546", "213465", "213546", "214356", "214365"]
weight = 1
show = false

# Named Rows
[[music]]
patterns = [ "123456", "132546", "135246", "142536", # Rounds, Priory/The Intermediate, Queens, Tittums
             "145236", "154326", "213546", "321456", # Jacks, Jokers, Burdette, See-saw
             "341256", "342516", "531246", "532146", # Hagdyke, Exploded Tittums, Kings/Whittingtons, Princes
             "654321" ]                              # Backrounds
weight = 1
show = false
