# Music file for 8-bell complib music compositions
# Music is plit into two scetions, the first gives what music to display in the header (which has zero
# weighting) and the second gives the scoring that counts towards the total music score.

#--------------------------#
#- Displayed header music -#
#--------------------------#

# crus
[[music]]
name = "CRUs"
patterns = ["4578*", "*4578", "4678*", "*4678", "5478*", "*5478",
            "5678*", "*5678", "6478*", "*6478", "6578*", "*6578"]
weight = 0

# Display 5678s
[[music]]
patterns = ["5678*", "*5678"]
weight = 0

# Display 6578s
[[music]]
patterns = ["6578*", "*6578"]
weight = 0

# 4-bell runs
[[music]]
run_length = 4
weight = 0

# Display total 5678 combinations
[[music]]
preset = "5678 combinations"
weight = 0

# Display 8765s
[[music]]
patterns = ["8765*", "*8765"]
weight = 0

#-----------------#
#- Music scoring -#
#-----------------#

# 56s & 65s
[[music]]
patterns = ["5678*", "*5678", "6578*", "*6578"]  # Boost 5678s and 6578s
show = false

# crus
[[music]]
name = "CRUs"
patterns = ["4578*", "*4578", "4678*", "*4678", "5478*", "*5478",
            "5678*", "*5678", "6478*", "*6478", "6578*", "*6578"]  # Boost 5678s, 4678s, 5478s, 5678s, 6478s and 6578s
show = false

# 4, 5, 6, and 7 Bell Runs
[[music]]
run_lengths = [4, 5, 6, 7]
show = false

# Combination Near Misses
[[music]]
patterns = ["12345687", "12345768", "12346578", "12354678", "12435678", "13245678",
            "21345678", "12346587", "12354768", "12435687", "12436578", "12436587",
            "13245768", "13254768", "21345687", "21346587", "21436587"]
show = false

# 5678 combinations counted towards music score
[[music]]
patterns = ["5678*", "*5678", "6578*", "*6578",  # From 5678 and 6578
            "7568*", "*7568", "7658*", "*7658",  # From 7568, 7658
            "8765*", "*8765"]                    # From 8765
show = false

# Combinations from named rows
[[music]]
patterns = ["*1357", "*2468", "*3468", "*3478",  # From Queens, Whittingtons, Hagdyke
            "*3578", "*5768", "*7468", "*7568",  # From 3578s, Bowbells, Princesses, Burdette
            "*7658", "*8765", "x5x6x7x8"]        # From Rollercoaster, Esso-Blues, tittums
show = false

# Named Rows
[[music]]
patterns = [ "12345678", "12563478", "12753468", "13245768",  # Rounds, Hagdyke, Whittingtons, Bowbells
             "13254768", "13527468", "13572468", "14327658",  # Priory/The Intermediate, Princesses, Queens, Rollercoaster
             "15263748", "16745238", "17652438", "17654328",  # Tittums, Jacks, St Michael's, Jokers
             "31247568", "43215678", "56781234", "45362718",  # Burdette, See-saw, Saw-see, Exploded Tittums
             "65432178", "75312468", "75321468", "87123456",  # Reverse Waterfall, Kings, Princes, Waterfall
             "87654321" ]                                     # Backrounds
show = false
