# Music file for 10-bell complib music compositions
# Music is split into two sections, the first gives what music to display in the header (which has zero
# weighting) and the second gives the scoring that counts towards the total music score.

#--------------------------#
#- Displayed header music -#
#--------------------------#

# Display 56s
[[music]]
pattern = "567890"
name = "56s"

# Display 65s
[[music]]
pattern = "657890"
name = "65s"

# 4-bell Runs
[[music]]
run_length = 4

# Display 09s at back
[[music]]
pattern = "09"
stroke = "back"
weight.back = 0

#-----------------#
#- Music scoring -#
#-----------------#

# 5, 6, 7, 8 and 9 Bell Runs
[[music]]
run_lengths = [5, 6, 7, 8, 9]
show = false

# Near Misses
[[music]]
patterns = ["1234567809", "1234567980", "1234568790", "1234576890", "1234657890", "1235467890",
            "1243567890", "1324567890", "2134567890"]
show = false

# Combinations from named rows
[[music]]
patterns = ["24680", "975680"]  # From Queens, Whittingtons
weight.back = 1
show = false
[[music]]
pattern = "x5x6x7x8x9x0" # From tittums
show = false

# Named Rows
[[music]]
patterns = ["1234567890", "1256349078", "1286349750", "1325476980", # Rounds, Hagdyke, Heywood's, Priory/The Intermediate
            "1357294680", "1357924680", "1539742860", "1627384950", # Princesses, Queens, Kennet, Tittums
            "1864297530", "1875296430", "1896745230", "1987654320", # Yeovil Octaves, Hereford Octaves, Jacks, Jokers
            "3124586790", "3124975680", "3216549870", "5432167890", # Burdette, Whittingtons, Rollercoaster, See-saw
            "5647382910", "6543217890", "9753124680", "9753214680", # Exploded Tittums, Reverse Waterfall, Kings, Princes
            "0987123456", "0987654321" ]                            # Waterfall, Backrounds
show = false
