[[music]]
run_length = 4

[[music]]
run_lengths = [5, 6]
show = false # Only show 4-bell runs

[[music]]
pattern = "56"
weight.back = 0.2

[[music]]
pattern = "65"
weight.back = -0.5
stroke = "back"

[[music]]
# Queens, 'whittingtons', exploded tittums and tittums
patterns = ["135246", "531246", "342516", "142536"]
weight.front = 3
show = false
