[[music]]
run_length = 4

[[music]]
run_lengths = [5, 6, 7, 8, 9, 10, 11, 12]
show = false # Only show 4-bell runs

# Counting 67890ETs as 7-bell runs tends to make Monument generate very static compositions, leaving 6
# unaffected for as long as possible.  So we nerf 7890ETs generally to encourage it to generate more
# interesting comps
[[music]]
patterns = ["TE0987*", "*7890ET"]
weight = -2
show = false

# Boost scores of LB5s in order to make Monument generate more of them (this and nerfing 67890s will
# make Monument prefer LB5 courses over just keeping the 6 at home for ages).
[[music]]
patterns = [
    "*65432", "23456*",
    "*23456", "65432*",
    "*76543", "34567*",
]
weight = 3
name = "lb5s"

[[music]]
pattern = "*567890ET"
name = "56s"

[[music]]
pattern = "*657890"
name = "65s"

[[music]]
pattern = "*TE"
stroke = "back"
weight = -0.7
show = false
